### ISSUE TITLE
No Raw Bitcoin Transaction after WIF Private Key Field

### ISSUE THREAD

**Issue by bitwyz** [coinables/coldsigner#1]
I was following all your steps successfully till your step "## 9. Lastly, enter the corresponding WIF private key from which address you are spending from into the WIF Private Key field. Click sign. The result is your raw bitcoin transaction." However, there was no raw output coming out. I used an offline machine.
![Coldsigner_issue](https://user-images.githubusercontent.com/39456369/80898327-8c4e9f00-8d34-11ea-8ac6-095bf66a1a0b.png)

**Comment by coinables** [comment]
Your network is selected as testnet but you are using a mainnet output address. Double-check your transaction network is consistent throughout.

**Comment by bitwyz** [comment]
Oh I see. So if it's testnet, all addresses should all be testnet as well. Is this the same principle as the signor.html?

**Comment by coinables** [comment]
Yes absolutely. One cannot spend testnet coins on mainnet or vice-versa.
